### ISSUE TITLE
The HTTP Request lab

### ISSUE THREAD

**Issue by WildBeanOnIt** [learn-co-curriculum/rack-http-request-readme#9]
### Canvas Link

https://learning.flatironschool.com/courses/1880/pages/the-http-request?module_item_id=259275

### Concern

Hi hello when I was doing the lab and going alone with it when I would run the code for the server and type 'search?q=Carrots' It would give me the 'Couldn't find Carrots' and I went back to the code and instead of having Apple, Carrots, and Pears with a capital letter it wouldnt work so I changed them to a lowercase and the code worked when I typed apple with lowercase I got 'carrots is one of our items' so I want to say it was the letters that were capitalized.

### Suggested Changes

should changed Apple, Carrots, and Pears to a lowercase so the code can work and other students wont get confused like I was. Thank you

**Comment by AlveeM** [comment]
Hi @WildBeanOnIt, thanks for submitting the issue.

We'd suggest modifying your code to account for both uppercase and lowercase letters. This is because you won't always have control over the data you're provided with or the data you get from APIs. 

Check out [this StackOverflow question](https://stackoverflow.com/questions/2844507/how-to-compare-strings-ignoring-the-case) to get some ideas on how to adapt your code to different cases.

If you have any further questions or clarifications, feel free to add comments to this issue.
